name: Package Python Project

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Zip project files
        run: |
          mkdir bundle
          cp -r modules bundle/modules
          cp manifest.json config.json __init__.py bundle/
          cd bundle

      - name: Upload artifact (uncompressed folder)
        uses: actions/upload-artifact@v4
        with:
          name: anki-incontext-kanji-${{ github.run_number }}
          path: bundle/