name: Package Python Project

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Zip project files
        run: |
          mkdir bundle
          cp -r modules bundle/modules
          cp manifest.json config.json bundle/
          cd bundle
          zip -r ../project-bundle.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-project-bundle
          path: project-bundle.zip
